version: '3.6'
services:
  elastic:
    image: pycontribs/ubuntu
    container_name: elastic-01
    hostname: elastic-01
    restart: unless-stopped
    entrypoint: "sleep infinity"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      elk_sub01:

  kibana:
    image: pycontribs/ubuntu
    container_name: kibana-01
    hostname: kibana-01
    restart: unless-stopped
    entrypoint: "sleep infinity"
    ports:
      - "5601:5601"
    networks:
      elk_sub01:

networks:
  elk_sub01:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.22.22.0/24
