version: '3.6'
services:
  elastic:
    image: pycontribs/ubuntu
    container_name: elastic-01
    hostname: elastic-01
    restart: unless-stopped
    entrypoint: "sleep infinity"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
#      elk_Network:
      default:

  kibana:
    image: pycontribs/ubuntu
    container_name: kibana-01
    hostname: kibana-01
    restart: unless-stopped
    entrypoint: "sleep infinity"
    ports:
      - "5601:5601"
    networks:
#      elk_Network:
      default:

  logstash:
    image: pycontribs/ubuntu
    container_name: logstash-01
    hostname: logstash-01
    restart: unless-stopped
    entrypoint: "sleep infinity"
    ports:
      - "5000:5000"
      - "9600:9600"
    networks:
#      elk_Network:
      default:

networks:

#  elk_Network:
#    driver: bridge
#    disable_ipv6: true
#    internal: true
#    ipam:
#     driver: default
#     config:
#       - subnet: 172.16.238.0/24
  default:
    driver: bridge
