version: '3'
services:
  elastic:
    image: pycontribs/ubuntu
    container_name: elastic-01
    restart: unless-stopped
    entrypoint: "sleep infinity"

  kibana:
    image: pycontribs/ubuntu
    container_name: kibana-01
    restart: unless-stopped
    entrypoint: "sleep infinity"

  logstash:
    image: pycontribs/ubuntu
    container_name: logstash-01
    restart: unless-stopped
    entrypoint: "sleep infinity"
