---
- name: Install Java
  hosts: all
  tasks:
    - name: Set facts for Java DK vars
      ansible.builtin.set_fact:
        java_home: "/opt/jdk/{{ java_jdk_version }}"
      tags:
        - java
    - name: Upload .tar.gz file containing binaries from local storage
      ansible.builtin.copy:
        src: "{{ java_oracle_jdk_package }}"
        dest: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
        mode: '0644'
      register: download_java_binaries
      until: download_java_binaries is succeeded
      tags:
        - java
#        - never
    - name: Ensure installation dir exists
      become: true
      ansible.builtin.file:
        state: directory
        path: "{{ java_home }}"
        mode: '0755'
      tags: java
    - name: Extract java in the installation directory
      become: true
      ansible.builtin.unarchive:
        copy: false
        src: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
        dest: "{{ java_home }}"
        extra_opts: [--strip-components=1]
        creates: "{{ java_home }}/bin/java"
      tags:
        - java
    - name: Export environment variables
      become: true
      ansible.builtin.template:
        src: jdk.sh.j2
        dest: /etc/profile.d/jdk.sh
        mode: '0755'
      tags: java
- name: Install Elasticsearch
  hosts: elasticsearch
  tasks:
    - name: Upload tar.gz Elasticsearch from remote URL
      ansible.builtin.get_url:
        url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
        dest: "/tmp/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
        mode: '0644'
        timeout: 60
        force: true
        validate_certs: false
      register: get_elastic
      until: get_elastic is succeeded
      tags:
        - elastic
#        - never
    - name: Create directrory for Elasticsearch
      ansible.builtin.file:
        state: directory
        path: "{{ elastic_home }}"
        mode: '0755'
      tags: elastic
    - name: Extract Elasticsearch in the installation directory
      become: true
      ansible.builtin.unarchive:
        copy: false
        src: "/tmp/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
        dest: "{{ elastic_home }}"
        extra_opts: [--strip-components=1]
        creates: "{{ elastic_home }}/bin/elasticsearch"
      tags:
        - elastic
    - name: Set environment Elastic
      become: true
      ansible.builtin.template:
        src: templates/elk.sh.j2
        dest: /etc/profile.d/elk.sh
        mode: '0755'
      tags: elastic
- name: Install Kibana
  hosts: kibana
  tasks:
    - name: Upload tar.gz Kibana from remote URL
      ansible.builtin.get_url:
        url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
        dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
        mode: '0644'
        timeout: 60
        force: true
        validate_certs: false
      register: get_kibana
      until: get_kibana is succeeded
      tags:
        - kibana
 #       - never
    - name: Create directrory for Kibana ({{ kibana_home }})
      ansible.builtin.file:
        path: "{{ kibana_home }}"
        state: directory
        mode: '0755'
      tags: kibana
    - name: Extract Kibana in the installation directory
      become: true
      ansible.builtin.unarchive:
        copy: false
        src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
        dest: "{{ kibana_home }}"
        extra_opts: [--strip-components=1]
        creates: "{{ kibana_home }}/bin/kibana"
      tags: kibana
    - name: Set environment Kibana
      become: true
      ansible.builtin.template:
        src: templates/kib.sh.j2
        dest: /etc/profile.d/kib.sh
        mode: '0755'
      tags: kibana
- name: Install Elasticsearch
  hosts: elasticsearch
  tasks:
    - name: Get IP address for elastic host
      ansible.builtin.shell: hostname -I
      register: elastic_ip_address
      tags:
        - logstash
- name: Install Logstash
  hosts: logstash
  tasks:
    - name: Upload tar.gz logstash from remote URL
      ansible.builtin.get_url:
        url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
        dest: "/tmp/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
        mode: '0644'
        timeout: 60
        force: true
        validate_certs: false
      register: get_logstash
      until: get_logstash is succeeded
      tags:
        - logstash
#        - never
    - name: Create directrory for logstash ({{ logstash_home }})
      ansible.builtin.file:
        path: "{{ logstash_home }}"
        state: directory
        mode: '0755'
      tags: logstash
    - name: Extract logstash in the installation directory
      become: true
      ansible.builtin.unarchive:
        copy: false
        src: "/tmp/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
        dest: "{{ logstash_home }}"
        extra_opts: [--strip-components=1]
        creates: "{{ logstash_home }}/bin/logstash"
      tags: logstash
    - name: Set environment logstash
      become: true
      ansible.builtin.template:
        src: templates/logstash.sh.j2
        dest: /etc/profile.d/logstash.sh
        mode: '0755'
      tags: logstash
    - name: Set config logstash
      ansible.builtin.template:
        src: templates/logstash.conf.j2
        dest: "{{ logstash_home }}/logstash.conf"
        mode: '0644'
      tags: logstash
